name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: oracle
      - run: |
          mvn package

          OPTIONS="--add-opens=java.base/jdk.internal.access=ALL-UNNAMED \
            --add-opens=java.base/jdk.internal.misc=ALL-UNNAMED \
            --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
            --add-opens=java.base/sun.util.calendar=ALL-UNNAMED \
            --add-opens=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED \
            --add-opens=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED \
            --add-opens=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED \
            --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED \
            --add-opens=java.base/java.io=ALL-UNNAMED \
            --add-opens=java.base/java.nio=ALL-UNNAMED \
            --add-opens=java.base/java.net=ALL-UNNAMED \
            --add-opens=java.base/java.util=ALL-UNNAMED \
            --add-opens=java.base/java.util.concurrent=ALL-UNNAMED \
            --add-opens=java.base/java.util.concurrent.locks=ALL-UNNAMED \
            --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED \
            --add-opens=java.base/java.lang=ALL-UNNAMED \
            --add-opens=java.base/java.lang.invoke=ALL-UNNAMED \
            --add-opens=java.base/java.math=ALL-UNNAMED \
            --add-opens=java.sql/java.sql=ALL-UNNAMED \
            --add-opens=java.base/java.lang.reflect=ALL-UNNAMED \
            --add-opens=java.base/java.time=ALL-UNNAMED \
            --add-opens=java.base/java.text=ALL-UNNAMED \
            --add-opens=java.management/sun.management=ALL-UNNAMED \
            --add-opens java.desktop/java.awt.font=ALL-UNNAMED"
          
          java $OPTIONS -classpath target/apache-ignite-example-*-jar-with-dependencies.jar org.moeaframework.ignite.IgniteMasterSlaveExample
          java $OPTIONS -classpath target/apache-ignite-example-*-jar-with-dependencies.jar org.moeaframework.ignite.IgniteIslandModelExample
